#!/usr/bin/env ruby
require 'fileutils'
require 'optparse'
require 'net/https'

options = {}
OptionParser.new do |opts|
  opts.on("--outdir THE_PATH", "the output directory") do |outdir|
    options[:outdir] = outdir
  end
end.parse!

def get_kiwi_archive(path)
  kiwi_archive = Dir[File.join(path, '/*.kiwi.txz')]
  if kiwi_archive.length > 1
    abort('More than one kiwi archives found')
  elsif kiwi_archive.length == 0
    abort('No kiwi archive found')
  end

  kiwi_archive[0]
end

def extract_archive(archive, outdir)
  system("tar", "Jxf", archive, "-C", outdir)
end

def create_root_archive(outdir)
  system("tar", "cf", File.join(outdir, 'root.tar'), "-C", File.join(outdir, 'root/'), "etc/", "studio/")
  FileUtils.rm_rf(File.join(outdir, 'root'))
end

def rename_kiwi_config(outdir)
  File.rename(File.join(outdir, 'config.xml'), File.join(outdir, 'config.kiwi'))
end

def order_kiwi_repos(outdir, limit = 5)
  api_url = ENV["OBS_SERVICE_APIURL"]

  unless api_url
    abort("No API url defined. This might be caused by using an older osc version.")
  end

  kiwi_config = File.join(outdir, 'config.kiwi')
  response = request_order_kiwi_repos(api_url, kiwi_config)

  while response.kind_of?(Net::HTTPRedirection) && limit > 0
    response = request_order_kiwi_repos(response['location'], kiwi_config)
    limit -= 1
  end

  if response.code.to_i == 200
    File.write(kiwi_config, response.body)
  else
    abort("Ordering kiwi repositories failed. Backend responded with '#{response.code} - #{response.message}'")
  end
end

def request_order_kiwi_repos(url, kiwi_config)
  uri = URI.parse(url)

  https = Net::HTTP.new(uri.host, uri.port)
  https.use_ssl = (uri.scheme == "https")

  request = Net::HTTP::Post.new("/source?cmd=orderkiwirepos")
  request.body = File.read(kiwi_config)
  request.content_type = "text/xml"

  https.request(request)
end

current_path = Dir.pwd
outdir = options[:outdir]
unless File.directory?(outdir) || File.exist?(outdir)
  abort("Output directory does not exist")
end

kiwi_archive = get_kiwi_archive(current_path)
extract_archive(kiwi_archive, outdir)
create_root_archive(outdir)
rename_kiwi_config(outdir)
order_kiwi_repos(outdir)

